spring:
  application:
    name: rest-logging-in-spring-way

server:
  port: 8090

app:
  integration:
    httpbin:
      url: http://localhost:8091
#logging:
#  level:
#    org:
#      springframework:
#        web:
#          filter:
#            CommonsRequestLoggingFilter: DEBUG