spring:
  application:
    name: rest-logging-in-spring-way
  docker:
    compose:
      file: compose.yaml

server:
  port: 8090

app:
  integration:
    httpbin:
      url: http://localhost:8091

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}